name: Build cvemap for linux

on:
  push:
    branches:
      - gh_workflow_test
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x  # Use the desired Go version

      - name: Build cvemap
        run: go build -o cvemap main.go
        working-directory: ${{ github.workspace }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: cvemap
          path: ./cvemap
